name: Push packages to Nuget

on: 
  push:
    tags:
    - 'v*'
    
env:
  PACKAGE_OUTPUT_DIRECTORY: ${{ github.workspace }}/artifacts
  NUGET_SOURCE_URL: 'https://api.nuget.org/v3/index.json'
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: 'Push'
      run: dotnet nuget push ${{ env.PACKAGE_OUTPUT_DIRECTORY }}/*.nupkg -k ${{ secrets.BARTECO_NUGET_API_KEY }} -s ${{ env.NUGET_SOURCE_URL }}
